export const CONNECTION_STATUS = 'CONNECTION_STATUS';

export const FETCH_DECLINED_PERMISSION = 'FETCH_DECLINED_PERMISSION';
export const FETCH_DECLINED_PERMISSION_SUCCESS = 'FETCH_DECLINED_PERMISSION_SUCCESS';
export const FETCH_DECLINED_PERMISSION_FAIL = 'FETCH_DECLINED_PERMISSION_FAIL';
export const FETCH_DECLINED_PERMISSION_START = 'FETCH_DECLINED_PERMISSION_START';

export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';