export const CONNECTION_STATUS = 'CONNECTION_STATUS';

export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';